;METADATA=(Diff=true, UseCommands=true)
[/Script/FortniteGame.FortGameUserSettings]
FullscreenMode=0
CosmeticStreamingEnabled=CodeSet_Disabled
FortniteReleaseVersion=14
UnlockConsoleFPS=False
SubGameSelectCount_Athena=14
SubGameLastSelectedTime_Athena=2026.06.26-00.02.51
SubGameSelectCount_Campaign=0
SubGameLastSelectedTime_Campaign=0001.01.01-00.00.00
LastTimeSettingsSnapshotUploaded=2026.06.26-04.02.52
LastTimeLockerPresetCountUploaded=2026.06.26-03.50.21
FirstLoginOnDevice=2025.09.27-18.00.06
SafeZone=1.000000
bIsSafeZoneSet=False
CachedPlayerLevel=0
bShowActorsWithSeasonItemTagMapIndicators=True
CachedBattleStars=0
CachedAlienStylePoints=0
CachedStylePoints=0
CachedClaimableRewards=()
CachedHighestBattlePassUnlockedPage=1
bShowCareerTabBang=False
bArmASREnabled=False
CustomVoiceChatInputDevice=
CustomVoiceChatOutputDevice=
CustomVoiceChatInputDeviceId=
CustomVoiceChatOutputDeviceId=
bMotionBlur=False
bAllowUIParallax=True
bShowGrass=False
bShowFPS=True
bUseGPUCrashDebugging=False
bStopRenderingInBackground=False
bLatencyTweak1=False
LatencyTweak2=2
bLatencyFlash=False
FortAntiAliasingMethod=Disabled
bEnableDLSSFrameGeneration=False
TemporalSuperResolutionQuality=Recommended
DLSSQuality=0
XeSSQuality=2
PotentiallyUpscaledResolutionQuality=100.000000
NeverUpscaledResolutionQuality=100.000000
bUseNanite=False
DesiredGlobalIlluminationQuality=0
DesiredReflectionQuality=0
PreNaniteGlobalIlluminationQuality=0
PreNaniteReflectionQuality=0
bRayTracing=False
b120FpsMode=False
FrontendFrameRateLimit=120
bIsEnergySavingEnabledIdle=False
bIsEnergySavingEnabledFocusLoss=False
EnergySavingLevelFocusLoss=1
DisplayGamma=2.200000
UserInterfaceContrast=1.000000
NamedTimes=()
NamedCounts=(("lastfrontendflow_Fortnite", 41),("lastfrontendflow_Fortnite_HotfixVer", 0),("UEnableMultiFactorModal::ShouldShowMFASplashScreen", 41),("UEnableMultiFactorModal::ShouldShowMFASplashScreen_HotfixVer", 0))
BattlePassOverrideTracker=0
NewestProgressiveCosmeticSetSeen=
CurrentLockerSortsByTag=()
ArchetypeShuffleSelectionBias=()
bLockerHideUnsupportedItems=False
bLockerSortItemsByRelevance=True
bHasUsedBattlePassCrewUpsellNavButton=False
LastExpectedShopRefreshTime=2025.11.03-00.00.00
bHasSeenItemShop=True
AboutShopModalVersionSeen=0
CurrentLockerFiltersByTag=()
bHasSeenJunoOutfitsFTUE=False
JunoFTUEQuestTrackingDisabledVersion=0
bHasSeenDonutShopSequence=False
DonutIdleGameHighScore=0.000000
RowIdToOfferSeenLevel=(("MrSavage-NEW.99", ItemShopVisited),("MrSavage-NEW.98", ItemShopVisited),("MrSavage-NEW.97", ItemShopVisited),("MrSavage-NEW.96", ItemShopVisited),("BestSellers.1", OfferSectionVisited),("Vans2xNEW.99", ItemShopVisited),("DPJuno.99", ItemShopVisited),("DPJuno.98", ItemShopVisited),("DPJuno.97", ItemShopVisited),("DPJuno.96", ItemShopVisited),("DPJuno.95", ItemShopVisited),("Deadpool&Wolverine1.99", ItemShopVisited),("Deadpool&Wolverine1.98", ItemShopVisited),("VictoryVibes0926.99", ItemShopVisited),("VictoryVibes0926.98", ItemShopVisited),("Jamtracks0927.99", ItemShopVisited),("Jamtracks0927.98", ItemShopVisited),("Jamtracks0927.97", ItemShopVisited),("Jamtracks0927.96", ItemShopVisited),("DeathZeroBatLaughHarley.99", ItemShopVisited),("DeathZeroBatLaughHarley.98", ItemShopVisited),("DeathZeroBatLaughHarley.97", ItemShopVisited),("Porsche918Spyder.99", ItemShopVisited),("Porsche918Spyder.98", ItemShopVisited),("BattleReady0927.99", ItemShopVisited),("BattleReady0927.98", ItemShopVisited),("BattleReady0927.97", ItemShopVisited),("BattleReady0927.96", ItemShopVisited),("BattleReady0927.95", ItemShopVisited),("BattleReady0927.94", ItemShopVisited),("BattleReady0927.93", ItemShopVisited),("CyberInfiltration.1", ItemShopVisited),("Boundless.99", ItemShopVisited),("Boundless.98", ItemShopVisited),("Boundless.97", ItemShopVisited),("Invincible1.99", ItemShopVisited),("Invincible1.98", ItemShopVisited),("Invincible1.97", ItemShopVisited),("Invincible1.96", ItemShopVisited),("Invincible1.95", ItemShopVisited),("Invincible1.94", ItemShopVisited),("Invincible1.93", ItemShopVisited),("MHANEW.99", ItemShopVisited),("MHANEW.98", ItemShopVisited),("MHANEW.97", ItemShopVisited),("MHANEW.96", ItemShopVisited),("MHANEW.95", ItemShopVisited),("MHANEW.94", ItemShopVisited),("MHANEW.93", ItemShopVisited),("VANESSUH\'SLOCKER.99", ItemShopVisited),("VANESSUH\'SLOCKER.98", ItemShopVisited),("LordZedd.99", ItemShopVisited),("ShocknAwesome.99", ItemShopVisited),("ShocknAwesome.98", ItemShopVisited),("ShocknAwesome.97", ItemShopVisited),("Boarderlands4.99", ItemShopVisited),("Boarderlands4.98", ItemShopVisited),("BatmobileOnly.99", ItemShopVisited),("DieselCar.99", ItemShopVisited),("SlitheryHotSpriteful.99", ItemShopVisited),("Gorillaz.99", ItemShopVisited),("Gorillaz.98", ItemShopVisited),("Gorillaz.97", ItemShopVisited),("Gorillaz.96", ItemShopVisited),("BattlePassCrew.1", ItemShopVisited),("BattlePassCrew.2", ItemShopVisited),("BattlePassCrew.3", ItemShopVisited),("BattlePassCrew.4", ItemShopVisited),("BattlePassCrew.5", ItemShopVisited),("LimitedTime.1", ItemShopVisited),("LimitedTime.2", ItemShopVisited),("LimitedTime.3", ItemShopVisited),("LimitedTime.4", ItemShopVisited),("LimitedTime.5", ItemShopVisited),("MrSavage.99", ItemShopVisited),("MrSavage.98", OfferSectionVisited),("MrSavage.97", ItemShopVisited),("MrSavage.96", ItemShopVisited),("BattleReady0928.99", OfferSectionVisited),("BattleReady0928.98", ItemShopVisited),("BattleReady0928.97", OfferSectionVisited),("BattleReady0928.96", ItemShopVisited),("BattleReady0928.95", ItemShopVisited),("BattleReady0928.94", ItemShopVisited),("BattleReady0928.93", OfferSectionVisited),("DeadWolvXmenGambitRogue.99", ItemShopVisited),("DeadWolvXmenGambitRogue.98", ItemShopVisited),("DeadWolvXmenGambitRogue.97", ItemShopVisited),("DeadWolvXmenGambitRogue.96", ItemShopVisited),("DeadWolvXmenGambitRogue.95", ItemShopVisited),("DeadWolvXmenGambitRogue.94", ItemShopVisited),("Rejekun.99", ItemShopVisited),("Rejekun.98", ItemShopVisited),("ZeroBatLaughHarley.99", ItemShopVisited),("ZeroBatLaughHarley.98", ItemShopVisited),("Vans2x.99", ItemShopVisited),("Jamtracks0928.99", ItemShopVisited),("Jamtracks0928.98", ItemShopVisited),("Jamtracks0928.97", ItemShopVisited),("Jamtracks0928.96", OfferSectionVisited),("Masamune.99", ItemShopVisited),("NoSweat0930.99", ItemShopVisited),("NoSweat0930.98", ItemShopVisited),("VictoryVibes0929.99", ItemShopVisited),("VictoryVibes0929.98", ItemShopVisited),("DeadWolvXmenGambitCuddle.99", ItemShopVisited),("DeadWolvXmenGambitCuddle.98", ItemShopVisited),("DeadWolvXmenGambitCuddle.97", ItemShopVisited),("DeadWolvXmenGambitCuddle.96", ItemShopVisited),("DeadWolvXmenGambitCuddle.95", ItemShopVisited),("DeadWolvXmenGambitCuddle.94", ItemShopVisited),("DeadWolvXmenGambitCuddle.93", ItemShopVisited),("DeadWolvXmenGambitCuddle.92", ItemShopVisited),("DeadWolvXmenGambitCuddle.91", ItemShopVisited),("DeadWolvXmenGambitCuddle.90", ItemShopVisited),("DeadWolvXmenGambitCuddle.89", ItemShopVisited),("DeadWolvXmenGambitCuddle.88", ItemShopVisited),("BattleReady0930.99", ItemShopVisited),("BattleReady0930.98", ItemShopVisited),("BattleReady0930.97", ItemShopVisited),("BattleReady0930.96", ItemShopVisited),("BattleReady0930.95", ItemShopVisited),("BattleReady0930.94", ItemShopVisited),("BattleReady0930.93", ItemShopVisited),("BattleReady0930.92", ItemShopVisited),("InkvilleGangT.99", ItemShopVisited),("BirdsofAFeather.99", ItemShopVisited),("BirdsofAFeather.98", ItemShopVisited),("BirdsofAFeather.97", ItemShopVisited),("BirdsofAFeather.96", ItemShopVisited),("Jamtracks0930.99", ItemShopVisited),("Jamtracks0930.98", ItemShopVisited),("Jamtracks0930.97", ItemShopVisited),("Jamtracks0930.96", ItemShopVisited),("SimpsonsBartNEW.99", ItemShopVisited),("SimpsonsBartNEW.98", ItemShopVisited),("SimpsonsBartNEW.97", ItemShopVisited),("SimpsonsBartNEW.96", ItemShopVisited),("Dayofthedead2NEW.99", ItemShopVisited),("Dayofthedead2NEW.98", ItemShopVisited),("MariahCarey.99", ItemShopVisited),("MariahCarey.98", ItemShopVisited),("KPop.99", ItemShopVisited),("KPop.98", ItemShopVisited),("KPop.97", ItemShopVisited),("KPop.96", ItemShopVisited),("FND1102.99", ItemShopVisited),("Alien.99", ItemShopVisited),("Alien.98", ItemShopVisited),("VV1031.99", ItemShopVisited),("VV1031.98", ItemShopVisited),("NS1028.99", Purchased),("NS1028.98", ItemShopVisited),("BR1102.99", ItemShopVisited),("BR1102.98", ItemShopVisited),("BR1102.97", ItemShopVisited),("JT01031.99", ItemShopVisited),("JT01031.98", ItemShopVisited),("JT01031.97", ItemShopVisited),("JT01031.96", ItemShopVisited),("Wednesday.99", ItemShopVisited),("Wednesday.98", ItemShopVisited),("Wednesday.97", ItemShopVisited),("Wednesday.96", ItemShopVisited),("ScoobyAll.99", ItemShopVisited),("ScoobyAll.98", ItemShopVisited),("ScoobyAll.97", ItemShopVisited),("ScoobyAll.96", OfferSectionVisited),("ScoobyAll.95", ItemShopVisited),("ScoobyAll.94", ItemShopVisited),("ScoobyAll.93", ItemShopVisited),("ScoobyAll.92", ItemShopVisited),("Billy.99", ItemShopVisited),("Billy.98", ItemShopVisited),("DodgeChargerSRTHellcat.99", ItemShopVisited),("Endo.99", ItemShopVisited),("Cristiano.99", ItemShopVisited),("DojaCatIcons.99", ItemShopVisited),("DojaCatIcons.98", ItemShopVisited),("DojaCatIcons.97", ItemShopVisited),("DojaCatIcons.96", ItemShopVisited),("DojaCatIcons.95", ItemShopVisited),("LimitedTime.6", ItemShopVisited))
LastSelectedIsland="{\"LinkId\":\"0761-8037-1605\",\"Session\":{\"iD\":\"\",\"joinInfo\":{\"joinability\":\"CanNotBeJoinedOrWatched\",\"sessionKey\":\"\"}},\"MatchmakingSettingsV2\":{\"/Fortnite.com/Matchmaking:Region\":\"NONE\"}}"
LastPlayedIsland="{\"LinkId\":\"0761-8037-1605\",\"Session\":{\"iD\":\"\",\"joinInfo\":{\"joinability\":\"CanNotBeJoinedOrWatched\",\"sessionKey\":\"\"}},\"MatchmakingSettingsV2\":{\"/Fortnite.com/Matchmaking:Region\":\"NONE\"}}"
LastSelectedPlaylist=(PlaylistName="NoPlaylist",TournamentID="",EventWindowId="",LinkId=(Mnemonic="0761-8037-1605",Version=-1),ProductModes=)
LastSelectedFillOption=True
bLastSelectedPrivateMatchOption=True
CustomMatchOptions=()
CreativeOptions=()
bHasSeenCreativePhoneTutorial=False
bHasSeenCreativeHeatmapTutorial=False
CreativeOptionLastUsedCategory=0
CreativeOptionLastUsedIndexInCategory=0
LastSelectedChildActivityMap=()
ClamOneDMVersion=1
ClamOneDMPreviousVersion=1
ClamOneDMMaxEvents=200
LastNewsVersionViewedBR=
LastNewsVersionViewedCreative=
LastNewsVersionViewedSTW=
LastPRMEtag=
LastFrontEndBackPlateStageUsed[0]=season4100
LastFrontEndBackPlateStageUsed[1]=default
bEulaAccepted=True
EulaAcceptedUserId=bb017ecac6644069a23e6aeef9e815da
LastEulaCheckTime=2026.06.26-03.50.21
HUDLayoutData[0]=(LayoutEntries=)
HUDLayoutData[1]=(LayoutEntries=)
HUDLayoutData[2]=(LayoutEntries=)
bHasBeenNotifiedAboutLegacyLayoutDeprecation=False
ActiveHUDProfileIdentifier=(HUDProfileType=(TagName=""),Guid=00000000000000000000000000000000)
bTimesSeenBacchusLoadTutorial=0
bHasSeenTapToShoot=False
NumTimesSeeingPanningTip=0
FireModeData=(bAutoFireIsEnabled=True,b3DTouchEnabled=False,bTapToShootEnabled=False,bAlwaysShowDedicatedButton=True,FireModeType=Unset)
SimpleMobileStats=(GamesPlayed=4,SecondsPlayed=2400,KillCount=11,BestResult=100,LastReviewPromptDay=0001.01.01-00.00.00,CampaignGamesPlayed=0)
SelectedAndroidAppStore=Unset
AudioOutputDeviceId=
bUseHeadphoneMode=False
InitialBenchmarkState=1
bDisableMouseAcceleration=False
ChosenLoginType=None
SocialImportOptedOutVersion=0
VKImportOptedOutVersion=0
bHasSeenErebusSocialImport=False
bHasSeenFriendImportToast=False
LastSocialImportPromptTime=0001.01.01-00.00.00
bAutoImportFriendEnabled=False
bSeenLetoSellModal=False
SocialImportPromptCountCurrentVersion=0
SocialImportPromptCountAllVersions=0
VKImportPromptCountCurrentVersion=0
VKImportPromptCountAllVersions=0
LastAccountItemWarningTime=0001.01.01-00.00.00
bMultiFactorAuthModalOpOut=False
LastEnableMFAModalPromptTime=0001.01.01-00.00.00
LastVKImportPromptTime=0001.01.01-00.00.00
LastAffiliateToastTime=0001.01.01-00.00.00
FailedInviteMap=()
MobileRecommendationDismissedVersion=0
ShowLiveStreamPictureInPictureInMatchV2=Default
CurrentLivePiPStreamOverrideCounter=0
SelectedFrontEnd=
bNeverShowMobileLink=False
bHasMigratedDownloadSettings=False
bSendAppsFlyerEventOnInstallation=True
bAllowFullGameDownload=False
ReducedDataUsage=UnSet
bAllowCellularDownload=False
LastAutoDownloadHighResTextureReminder=639180433898440000
bOverrideMobileScalabilityForNewUser=False
bShouldTryShowMobileDefaultSettingsChanged=False
bAutoLaunchFullGame=False
bAllowDownloadHighResMips=False
ContentQualityLevelSelected=Unset
bAllowLowPowerMode=False
bAllowVideoPlayback=True
MobileFPSMode=Mode_30Fps
MobileQualitySettingsResetDefaultsGUID=
bHasSeenSamsungPressureSensorWarning=False
bNeverDisplaySamsungPressureSensorWarning=False
bHasRecentlySeenBadMatchPopup=False
MatchesSinceLastBadMatchPopup=0
bHasAlreadyRatedOnGooglePlay=False
DaysToSnoozeBeforeNextGooglePlayRating=0
GooglePlayRatingDelayedOccurences=0
ParsleyIdleTime=Never
bShowTemperature=False
LastGameStartNotificationSentTime=0001.01.01-00.00.00
LastYearForcedDisplayWinterfestInfoButton=0
LastYearWinterfestWasSeen=0
bHasSeenSidekickWelcomePopup=False
bHasSeenLobbyModeSetNotification=False
bHasSeenLobbyModeChangedNotification=False
bHasSeenDiscoveryDetailsModeSetNotification=True
bHasSeenDiscoveryCCUModal=False
bHasSeenCreatorPageFirstTimeTooltip=True
LowInputLatencyModeIsEnabled=True
bNeedsToSeeFireModeSelectionReminder=False
MatchesSinceInitialFireModeSelection=0
LastLaunchPushNotificationState=NotSet
bIsPushNotificationConsentValid=False
SavedVariantOverridesMap=()
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=2000
ResolutionSizeY=1440
LastUserConfirmedResolutionSizeX=2000
LastUserConfirmedResolutionSizeY=1440
LastConfirmedFullscreenMode=0
PreferredFullscreenMode=0
AudioQualityLevel=0
LastConfirmedAudioQualityLevel=0
FrameRateLimit=0.000000
DesiredScreenWidth=2000
DesiredScreenHeight=1440
LastUserConfirmedDesiredScreenWidth=2000
LastUserConfirmedDesiredScreenHeight=1440
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=263.837250
LastGPUBenchmarkResult=787.820801
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
LastUserConfirmedDisplayIndex=0
DynamicResolutionFrameTarget=0.000000
EulaCacheVersion=1
TextureQualityLevel=UnSet
DisplayID="MONITOR\\SAM74A7\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005"
DisplayIndex=0
LastUserConfirmedDisplayID="MONITOR\\SAM74A7\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005"
HDRUILuminanceNits=203.000000
LastCPUBenchmarkSteps=239.709595
LastCPUBenchmarkSteps=279.922333
HasSeenAboutItemModalTypes=()
bIsHDRUILuminanceSeparate=False
bShowCareerV3TabBang=False
GlobalConfigData=()
bShowCareerShowcaseTabBang=True
ArmASRQuality=1
QualcommGSRQuality=1
ClamOneDMViewedEvents=13012480271557544748
HDRPaperWhiteNits=203.000000
RecentSelections="(Island={\"LinkId\":\"experience_br\",\"Session\":{\"iD\":\"\",\"joinInfo\":{\"joinability\":\"CanNotBeJoinedOrWatched\",\"sessionKey\":\"\"}},\"MatchmakingSettingsV2\":{\"/Fortnite.com/Matchmaking:SquadFill\":\"Fill\",\"/Fortnite.com/Matchmaking:Ranked\":\"Unranked\",\"/Fortnite.com/BattleRoyale/Matchmaking:TeamSize\":\"Squad\",\"/Fortnite.com/BattleRoyale/Matchmaking:BuildMode\":\"Build\",\"/Fortnite.com/Matchmaking:Region\":\"NAE\"}},Timestamp=1782446575,bUsingGracefulUpgrade=True,MatchmakingId=\"87342A3F464CB71028581A9CF804636A\")"
bUseHDRDisplayCalibration=False
LastGPUBenchmarkSteps=1526.214478
LastGPUBenchmarkSteps=1038.714478
LastGPUBenchmarkSteps=1918.248413
LastGPUBenchmarkSteps=660.014893
LastGPUBenchmarkSteps=294.712738
LastGPUBenchmarkSteps=456.418060
LastGPUBenchmarkSteps=1834.946289

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=0
sg.FoliageQuality=3
sg.ShadingQuality=0
sg.LandscapeQuality=0

[/Script/FortniteUIAudio.FortAudioUserMixSubsystem]
UserMixCurrentValues=(BusName="CB_Slider_Main",Volume=0.700000)
UserMixCurrentValues=(BusName="CB_Slider_Chat",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_Cinematics",Volume=0.730000)
UserMixCurrentValues=(BusName="CB_Slider_Dialogue",Volume=0.700000)
UserMixCurrentValues=(BusName="CB_Slider_Music",Volume=0.210000)
UserMixCurrentValues=(BusName="CB_Slider_PIP",Volume=0.500000)
UserMixCurrentValues=(BusName="CB_Slider_SFX",Volume=0.740000)
UserMixCurrentValues=(BusName="CB_IsInFrontend",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_LobbyMusic",Volume=0.700000)

[ChatSettings]
HideSocialName=False
AutoImportFriends=False
ShowNotifications=True
NeverFadeMessages=False
ShowTimeStamps=True
ShowWhispersInAllTabs=False
ShowCustomTab=True
ShowWhispersTab=False
ShowGlobalTab=True
ShowCombatAndEventsTab=True
ShowClanTabs=True
HideOffline=False
HideOutgoing=False
HideSuggestions=False
HideRecent=False
HideBlocked=True
FilterMatureLanguage=True
DisplayCharacterNames=False
FriendInviteReceivedCueEnabled=True
GameOrPartyInviteReceivedCueEnabled=False
MessageReceivedCueEnabled=True
SoundEnabled=False
ShowTextChat=True
FontSize=1
WindowHeight=0
WindowOpacity=0.5

[D3DRHIPreference]
PreferredRHI=dx11
PreferredFeatureLevel=es31

[DriverCache]
LastSeasonClear=38

[/Script/FortniteUIAudio.FortAudioUserMixGameUserSettings]
Version=1
UserMixCurrentValues=(BusName="CB_Slider_Main",Volume=0.130000)
UserMixCurrentValues=(BusName="CB_Slider_Chat",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_Cinematics",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_Dialogue",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_Music",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_PIP",Volume=0.500000)
UserMixCurrentValues=(BusName="CB_Slider_SFX",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_IsInFrontend",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_LobbyMusic",Volume=1.000000)

